from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from imagery_core import IMAGINE_SEC, load_sampling_rate, read_csv_with_fallback


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract IMAGINE 2-second EEG epochs using aligned pulses.")
    parser.add_argument(
        "--raw-dir",
        type=Path,
        default=Path("map/rawdata/RecordingS17R000_CSV"),
        help="Directory with wert_eeg.csv and info.json",
    )
    parser.add_argument(
        "--alignment-csv",
        type=Path,
        default=Path("map/analysis_results/trial_alignment.csv"),
        help="Alignment CSV generated by align_trials.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("map/analysis_results"),
        help="Output directory.",
    )
    parser.add_argument(
        "--imagine-sec",
        type=float,
        default=IMAGINE_SEC,
        help="Epoch length in seconds.",
    )
    return parser.parse_args()


def run_epoch_extraction(
    raw_dir: Path,
    alignment_csv: Path,
    out_dir: Path,
    imagine_sec: float = IMAGINE_SEC,
) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    fs = load_sampling_rate(raw_dir)

    eeg_df = read_csv_with_fallback(raw_dir / "wert_eeg.csv")
    align_df = read_csv_with_fallback(alignment_csv)

    eeg = eeg_df.to_numpy(dtype=np.float64).T  # [C, T]
    channel_names = [str(col).split("-", 1)[-1].strip() for col in eeg_df.columns.tolist()]
    epoch_len = int(round(imagine_sec * fs))

    epochs: list[np.ndarray] = []
    labels: list[int] = []
    trials: list[int] = []
    pulses: list[int] = []
    directions: list[str] = []
    manifest_rows: list[dict[str, Any]] = []

    for row in align_df.sort_values("trial_idx").itertuples(index=False):
        trial_idx = int(row.trial_idx)
        pulse_sample = int(row.pulse_sample)
        class_id = int(row.class_id)
        direction = str(row.direction) if hasattr(row, "direction") else ""
        start = pulse_sample
        end = start + epoch_len
        if end > eeg.shape[1]:
            manifest_rows.append(
                {
                    "trial_idx": trial_idx,
                    "pulse_sample": pulse_sample,
                    "class_id": class_id,
                    "direction": direction,
                    "status": "out_of_range",
                }
            )
            continue

        if class_id < 0:
            manifest_rows.append(
                {
                    "trial_idx": trial_idx,
                    "pulse_sample": pulse_sample,
                    "class_id": class_id,
                    "direction": direction,
                    "status": "invalid_label",
                }
            )
            continue

        epochs.append(eeg[:, start:end].astype(np.float32))
        labels.append(class_id)
        trials.append(trial_idx)
        pulses.append(pulse_sample)
        directions.append(direction)
        manifest_rows.append(
            {
                "trial_idx": trial_idx,
                "pulse_sample": pulse_sample,
                "class_id": class_id,
                "direction": direction,
                "status": "ok",
            }
        )

    if not epochs:
        raise RuntimeError("No valid epochs extracted. Check alignment and labels.")

    epochs_np = np.stack(epochs, axis=0)
    labels_np = np.array(labels, dtype=np.int64)
    trials_np = np.array(trials, dtype=np.int64)
    pulses_np = np.array(pulses, dtype=np.int64)
    directions_np = np.array(directions, dtype=object)

    out_npz = out_dir / "imagine_epochs_4class.npz"
    np.savez_compressed(
        out_npz,
        eeg_epochs=epochs_np,
        labels=labels_np,
        trial_idx=trials_np,
        pulse_sample=pulses_np,
        direction=directions_np,
        channel_names=np.array(channel_names, dtype=object),
        fs=np.array([fs], dtype=np.float64),
    )

    manifest_df = pd.DataFrame(manifest_rows)
    manifest_csv = out_dir / "epoch_manifest.csv"
    manifest_df.to_csv(manifest_csv, index=False, encoding="utf-8")

    summary = {
        "raw_dir": str(raw_dir),
        "alignment_csv": str(alignment_csv),
        "sampling_rate_hz": fs,
        "imagine_sec": float(imagine_sec),
        "epoch_len_samples": int(epoch_len),
        "total_alignment_rows": int(align_df.shape[0]),
        "valid_epochs": int(epochs_np.shape[0]),
        "class_counts": {
            int(k): int(v) for k, v in zip(*np.unique(labels_np, return_counts=True))
        },
        "shape": {
            "epochs": list(epochs_np.shape),
        },
    }

    summary_json = out_dir / "epoch_extraction_summary.json"
    with summary_json.open("w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print(f"fs={fs} Hz")
    print(f"epochs={epochs_np.shape}")
    print(f"class_counts={summary['class_counts']}")
    print(f"saved={out_npz}")
    print(f"saved={manifest_csv}")
    print(f"saved={summary_json}")

    return {
        "epochs_npz": out_npz,
        "manifest_csv": manifest_csv,
        "summary_json": summary_json,
        "summary": summary,
    }


def main() -> None:
    args = parse_args()
    run_epoch_extraction(
        raw_dir=args.raw_dir,
        alignment_csv=args.alignment_csv,
        out_dir=args.out_dir,
        imagine_sec=args.imagine_sec,
    )


if __name__ == "__main__":
    main()
