from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np

from imagery_core import BANDS_HZ, STEP_SEC, WINDOW_SEC, extract_feature_tensor


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compute Hilbert-based features from extracted IMAGINE EEG epochs.")
    parser.add_argument(
        "--epochs-npz",
        type=Path,
        default=Path("map/analysis_results/imagine_epochs_4class.npz"),
        help="Epoch NPZ generated by extract_imagine_epochs.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("map/analysis_results"),
        help="Output directory.",
    )
    parser.add_argument("--window-sec", type=float, default=WINDOW_SEC)
    parser.add_argument("--step-sec", type=float, default=STEP_SEC)
    return parser.parse_args()


def _to_str_list(values: np.ndarray) -> list[str]:
    out: list[str] = []
    for v in values.tolist():
        if isinstance(v, bytes):
            out.append(v.decode("utf-8"))
        else:
            out.append(str(v))
    return out


def run_feature_extraction(
    epochs_npz: Path,
    out_dir: Path,
    window_sec: float = WINDOW_SEC,
    step_sec: float = STEP_SEC,
) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)

    data = np.load(epochs_npz, allow_pickle=True)
    epochs = data["eeg_epochs"].astype(np.float64)
    labels = data["labels"].astype(np.int64)
    trials = data["trial_idx"].astype(np.int64)
    pulses = data["pulse_sample"].astype(np.int64)
    fs = float(np.asarray(data["fs"]).reshape(-1)[0])
    channel_names = _to_str_list(data["channel_names"])

    feature_tensor, window_starts = extract_feature_tensor(
        epochs=epochs,
        channel_names=channel_names,
        fs=fs,
        bands_hz=BANDS_HZ,
        window_sec=window_sec,
        step_sec=step_sec,
    )

    out_npz = out_dir / "imagine_features_4class.npz"
    np.savez_compressed(
        out_npz,
        feature_tensor=feature_tensor.astype(np.float32),  # [N, W, B, F]
        window_start_samples=window_starts.astype(np.int64),
        bands_hz=np.array(BANDS_HZ, dtype=np.float32),
        labels=labels.astype(np.int64),
        trial_idx=trials.astype(np.int64),
        pulse_sample=pulses.astype(np.int64),
        fs=np.array([fs], dtype=np.float64),
    )

    summary = {
        "epochs_npz": str(epochs_npz),
        "sampling_rate_hz": fs,
        "window_sec": float(window_sec),
        "step_sec": float(step_sec),
        "bands_hz": BANDS_HZ,
        "shape": {
            "feature_tensor": list(feature_tensor.shape),
            "window_count": int(window_starts.size),
        },
    }

    summary_json = out_dir / "feature_extraction_summary.json"
    with summary_json.open("w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print(f"feature_tensor_shape={feature_tensor.shape}")
    print(f"saved={out_npz}")
    print(f"saved={summary_json}")

    return {
        "features_npz": out_npz,
        "summary_json": summary_json,
        "summary": summary,
    }


def main() -> None:
    args = parse_args()
    run_feature_extraction(
        epochs_npz=args.epochs_npz,
        out_dir=args.out_dir,
        window_sec=args.window_sec,
        step_sec=args.step_sec,
    )


if __name__ == "__main__":
    main()
