from __future__ import annotations

import argparse
import json
import warnings
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pandas as pd
from scipy.signal import butter, hilbert, resample, sosfiltfilt
from sklearn.decomposition import PCA
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from imagery_core import (
    BANDS_HZ,
    HAS_TORCH,
    evaluate_sklearn_model,
    evaluate_torch_model,
)

if HAS_TORCH:
    from imagery_core import TemporalCNN, TemporalTransformer

    import torch
    from torch import nn


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train and evaluate 4-class imagery classifiers.")
    parser.add_argument(
        "--features-npz",
        type=Path,
        default=Path("map/analysis_results/imagine_features_4class.npz"),
        help="Feature NPZ generated by extract_imagery_features.py",
    )
    parser.add_argument(
        "--epochs-npz",
        type=Path,
        default=Path("map/analysis_results/imagine_epochs_4class.npz"),
        help="Epoch NPZ generated by extract_imagine_epochs.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("map/analysis_results"),
        help="Output directory.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-epochs", type=int, default=120)
    parser.add_argument("--no-torch", action="store_true", help="Skip CNN/Transformer models.")
    return parser.parse_args()


def _to_str_list(values: np.ndarray) -> list[str]:
    out: list[str] = []
    for v in values.tolist():
        if isinstance(v, bytes):
            out.append(v.decode("utf-8"))
        else:
            out.append(str(v))
    return out


def _downsample_epoch_seq(epochs: np.ndarray, factor: int) -> np.ndarray:
    if factor <= 1:
        return np.transpose(epochs, (0, 2, 1)).astype(np.float32)
    n, c, t = epochs.shape
    usable = (t // factor) * factor
    x = epochs[:, :, :usable].reshape(n, c, usable // factor, factor).mean(axis=3)
    return np.transpose(x, (0, 2, 1)).astype(np.float32)


def _sequence_diff(seq: np.ndarray) -> np.ndarray:
    return np.diff(seq, axis=1, prepend=seq[:, :1, :]).astype(np.float32)


def _resample_seq_time(seq: np.ndarray, target_len: int) -> np.ndarray:
    if seq.shape[1] == target_len:
        return seq.astype(np.float32)
    return resample(seq, target_len, axis=1).astype(np.float32)


def _bandpower_features(epochs: np.ndarray, fs: float) -> np.ndarray:
    n, c, _ = epochs.shape
    nyq = fs * 0.5
    feats = np.zeros((n, len(BANDS_HZ), c), dtype=np.float64)
    for bi, (lo, hi) in enumerate(BANDS_HZ):
        sos = butter(4, [lo / nyq, hi / nyq], btype="bandpass", output="sos")
        filtered = sosfiltfilt(sos, epochs, axis=2)
        power = np.mean(np.abs(hilbert(filtered, axis=2)) ** 2, axis=2)
        feats[:, bi, :] = np.log(power + 1e-9)
    return feats.reshape(n, -1).astype(np.float32)


def _asymmetry_features(epochs: np.ndarray, channel_names: list[str], fs: float) -> np.ndarray:
    pair_names = [("AF7", "AF8"), ("Fp1", "Fp2"), ("F3", "F4"), ("P3", "P4"), ("P7", "P8"), ("O1", "O2")]
    idx = {name: i for i, name in enumerate(channel_names)}
    pairs = [(idx[l], idx[r]) for l, r in pair_names if l in idx and r in idx]
    if not pairs:
        raise RuntimeError("No valid left-right channel pairs found for asymmetry features.")

    nyq = fs * 0.5
    n = epochs.shape[0]
    feats = np.zeros((n, len(BANDS_HZ), len(pairs)), dtype=np.float64)
    for bi, (lo, hi) in enumerate(BANDS_HZ):
        sos = butter(4, [lo / nyq, hi / nyq], btype="bandpass", output="sos")
        filtered = sosfiltfilt(sos, epochs, axis=2)
        power = np.mean(np.abs(hilbert(filtered, axis=2)) ** 2, axis=2)
        for pi, (li, ri) in enumerate(pairs):
            feats[:, bi, pi] = np.log((power[:, li] + 1e-9) / (power[:, ri] + 1e-9))
    return feats.reshape(n, -1).astype(np.float32)


def _temporal_slope(feature_tensor: np.ndarray) -> np.ndarray:
    # [N, W, B, F] -> [N, B, F]
    w = feature_tensor.shape[1]
    t = np.arange(w, dtype=np.float64)
    t = t - t.mean()
    denom = float(np.sum(t * t) + 1e-9)
    slope = np.tensordot(feature_tensor, t, axes=([1], [0])) / denom
    return np.transpose(slope, (0, 2, 1)).astype(np.float32)


def _concat_features(parts: list[np.ndarray]) -> np.ndarray:
    return np.concatenate(parts, axis=1).astype(np.float32)


def _build_tabular_inputs(
    feature_tensor: np.ndarray,
    epochs: np.ndarray,
    channel_names: list[str],
    fs: float,
) -> dict[str, np.ndarray]:
    n = feature_tensor.shape[0]
    mean_f = feature_tensor.mean(axis=1)
    std_f = feature_tensor.std(axis=1)
    min_f = feature_tensor.min(axis=1)
    max_f = feature_tensor.max(axis=1)
    delta_f = feature_tensor[:, -1, :, :] - feature_tensor[:, 0, :, :]
    slope_f = _temporal_slope(feature_tensor)
    q25_f = np.quantile(feature_tensor, 0.25, axis=1)
    q50_f = np.quantile(feature_tensor, 0.50, axis=1)
    q75_f = np.quantile(feature_tensor, 0.75, axis=1)

    hilbert_flat = feature_tensor.reshape(n, -1).astype(np.float32)
    hilbert_mean = mean_f.reshape(n, -1).astype(np.float32)
    hilbert_stats = _concat_features(
        [
            mean_f.reshape(n, -1),
            std_f.reshape(n, -1),
            delta_f.reshape(n, -1),
            slope_f.reshape(n, -1),
        ]
    )
    hilbert_quantiles = _concat_features(
        [
            q25_f.reshape(n, -1),
            q50_f.reshape(n, -1),
            q75_f.reshape(n, -1),
            min_f.reshape(n, -1),
            max_f.reshape(n, -1),
        ]
    )

    eeg_raw_ds2 = epochs[:, :, ::2].reshape(n, -1).astype(np.float32)
    eeg_raw_ds4 = epochs[:, :, ::4].reshape(n, -1).astype(np.float32)
    eeg_raw_diff_ds4 = np.diff(epochs[:, :, ::4], axis=2, prepend=epochs[:, :, ::4][:, :, :1]).reshape(n, -1).astype(np.float32)
    eeg_bandpower = _bandpower_features(epochs, fs=fs)
    eeg_asymmetry = _asymmetry_features(epochs, channel_names=channel_names, fs=fs)

    inputs = {
        "hilbert_flat": hilbert_flat,
        "hilbert_mean": hilbert_mean,
        "hilbert_stats": hilbert_stats,
        "hilbert_quantiles": hilbert_quantiles,
        "eeg_raw_ds2": eeg_raw_ds2,
        "eeg_raw_ds4": eeg_raw_ds4,
        "eeg_raw_diff_ds4": eeg_raw_diff_ds4,
        "eeg_bandpower": eeg_bandpower,
        "eeg_asymmetry": eeg_asymmetry,
        "combo_hilbert_band": _concat_features([hilbert_stats, eeg_bandpower]),
        "combo_hilbert_asym": _concat_features([hilbert_stats, eeg_asymmetry]),
        "combo_band_asym": _concat_features([eeg_bandpower, eeg_asymmetry]),
        "combo_all_dense": _concat_features([hilbert_stats, eeg_bandpower, eeg_asymmetry]),
        "combo_all_raw": _concat_features([hilbert_flat, eeg_raw_ds4]),
    }
    return inputs


def _build_sequence_inputs(feature_tensor: np.ndarray, epochs: np.ndarray) -> dict[str, np.ndarray]:
    n = feature_tensor.shape[0]
    hilbert_seq = feature_tensor.reshape(n, feature_tensor.shape[1], -1).astype(np.float32)
    eeg_seq_ds2 = _downsample_epoch_seq(epochs, factor=2)
    eeg_seq_ds4 = _downsample_epoch_seq(epochs, factor=4)
    eeg_seq_ds8 = _downsample_epoch_seq(epochs, factor=8)
    eeg_diff_ds4 = _sequence_diff(eeg_seq_ds4)

    target_len = hilbert_seq.shape[1]
    eeg4_res36 = _resample_seq_time(eeg_seq_ds4, target_len=target_len)
    eeg8_res36 = _resample_seq_time(eeg_seq_ds8, target_len=target_len)
    eeg4diff_res36 = _resample_seq_time(eeg_diff_ds4, target_len=target_len)

    seq_inputs = {
        "hilbert_seq": hilbert_seq,
        "eeg_seq_ds2": eeg_seq_ds2,
        "eeg_seq_ds4": eeg_seq_ds4,
        "eeg_seq_ds8": eeg_seq_ds8,
        "fusion_hilbert_eeg4_seq36": np.concatenate([hilbert_seq, eeg4_res36], axis=2).astype(np.float32),
        "fusion_hilbert_eeg8_seq36": np.concatenate([hilbert_seq, eeg8_res36], axis=2).astype(np.float32),
        "fusion_hilbert_eeg4diff_seq36": np.concatenate([hilbert_seq, eeg4_res36, eeg4diff_res36], axis=2).astype(np.float32),
    }
    return seq_inputs


def _make_logistic(seed: int, c: float, use_pca: bool) -> Pipeline:
    steps: list[tuple[str, Any]] = [("scaler", StandardScaler())]
    if use_pca:
        steps.append(("pca", PCA(n_components=0.95, random_state=seed)))
    steps.append(
        (
            "clf",
            LogisticRegression(
                solver="saga",
                l1_ratio=1.0,
                C=float(c),
                max_iter=8000,
                random_state=seed,
            ),
        )
    )
    return Pipeline(steps)


def _make_svm(seed: int, c: float, kernel: str, use_pca: bool) -> Pipeline:
    steps: list[tuple[str, Any]] = [("scaler", StandardScaler())]
    if use_pca:
        steps.append(("pca", PCA(n_components=0.95, random_state=seed)))
    steps.append(
        (
            "clf",
            SVC(
                C=float(c),
                kernel=kernel,
                gamma="scale" if kernel == "rbf" else "auto",
                random_state=seed,
            ),
        )
    )
    return Pipeline(steps)


def _make_mlp(seed: int, hidden: tuple[int, ...], alpha: float, use_pca: bool) -> Pipeline:
    steps: list[tuple[str, Any]] = [("scaler", StandardScaler())]
    if use_pca:
        steps.append(("pca", PCA(n_components=0.95, random_state=seed)))
    steps.append(
        (
            "clf",
            MLPClassifier(
                hidden_layer_sizes=hidden,
                activation="relu",
                alpha=float(alpha),
                learning_rate_init=1e-3,
                max_iter=2500,
                early_stopping=True,
                n_iter_no_change=40,
                random_state=seed,
            ),
        )
    )
    return Pipeline(steps)


def _evaluate_sklearn_input_search(
    model_name: str,
    candidates: list[dict[str, Any]],
    input_map: dict[str, np.ndarray],
    labels: np.ndarray,
    splitter: StratifiedKFold,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    search_rows: list[dict[str, Any]] = []
    best_result: dict[str, Any] | None = None
    best_score = -1.0

    for cand in candidates:
        input_name = str(cand["input_name"])
        architecture = str(cand["architecture"])
        estimator = cand["estimator"]

        x = input_map[input_name]
        result = evaluate_sklearn_model(model_name, estimator, x, labels, splitter)
        score = float(result["overall"]["balanced_accuracy"])
        search_rows.append(
            {
                "model": model_name,
                "architecture": architecture,
                "input_name": input_name,
                "accuracy": float(result["overall"]["accuracy"]),
                "balanced_accuracy": score,
                "f1_macro": float(result["overall"]["f1_macro"]),
            }
        )
        if score > best_score:
            best_score = score
            best_result = result
            best_result["input_name"] = input_name
            best_result["architecture"] = architecture

    if best_result is None:
        raise RuntimeError(f"No candidate evaluated for {model_name}")
    return best_result, search_rows


if HAS_TORCH:

    class ResidualTCNBlock(nn.Module):
        def __init__(self, channels: int, dilation: int, dropout: float) -> None:
            super().__init__()
            self.net = nn.Sequential(
                nn.Conv1d(channels, channels, kernel_size=3, padding=dilation, dilation=dilation),
                nn.BatchNorm1d(channels),
                nn.GELU(),
                nn.Dropout(dropout),
                nn.Conv1d(channels, channels, kernel_size=3, padding=dilation, dilation=dilation),
                nn.BatchNorm1d(channels),
                nn.Dropout(dropout),
            )
            self.act = nn.GELU()

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            return self.act(x + self.net(x))


    class ResidualTCN(nn.Module):
        def __init__(self, in_features: int, num_classes: int, hidden: int = 64) -> None:
            super().__init__()
            self.stem = nn.Sequential(
                nn.Conv1d(in_features, hidden, kernel_size=1),
                nn.BatchNorm1d(hidden),
                nn.GELU(),
            )
            self.blocks = nn.Sequential(
                ResidualTCNBlock(hidden, dilation=1, dropout=0.20),
                ResidualTCNBlock(hidden, dilation=2, dropout=0.20),
                ResidualTCNBlock(hidden, dilation=4, dropout=0.20),
                ResidualTCNBlock(hidden, dilation=8, dropout=0.20),
            )
            self.head = nn.Sequential(
                nn.AdaptiveAvgPool1d(1),
                nn.Flatten(),
                nn.Linear(hidden, num_classes),
            )

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            z = x.transpose(1, 2)
            z = self.stem(z)
            z = self.blocks(z)
            return self.head(z)


    class InceptionTemporalCNN(nn.Module):
        def __init__(self, in_features: int, num_classes: int, base: int = 24) -> None:
            super().__init__()
            self.b3 = nn.Conv1d(in_features, base, kernel_size=3, padding=1)
            self.b5 = nn.Conv1d(in_features, base, kernel_size=5, padding=2)
            self.b7 = nn.Conv1d(in_features, base, kernel_size=7, padding=3)
            self.bn1 = nn.BatchNorm1d(base * 3)
            self.mix = nn.Sequential(
                nn.Conv1d(base * 3, base * 3, kernel_size=1),
                nn.BatchNorm1d(base * 3),
                nn.GELU(),
                nn.Dropout(0.20),
                nn.Conv1d(base * 3, base * 3, kernel_size=3, padding=1),
                nn.BatchNorm1d(base * 3),
                nn.GELU(),
                nn.Dropout(0.20),
            )
            self.head = nn.Sequential(
                nn.AdaptiveAvgPool1d(1),
                nn.Flatten(),
                nn.Linear(base * 3, num_classes),
            )

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            z = x.transpose(1, 2)
            z = torch.cat([self.b3(z), self.b5(z), self.b7(z)], dim=1)
            z = torch.relu(self.bn1(z))
            z = self.mix(z)
            return self.head(z)


    class CLSTransformer(nn.Module):
        def __init__(
            self,
            in_features: int,
            seq_len: int,
            num_classes: int,
            d_model: int = 80,
        ) -> None:
            super().__init__()
            self.in_proj = nn.Linear(in_features, d_model)
            self.cls = nn.Parameter(torch.zeros(1, 1, d_model))
            self.pos = nn.Parameter(torch.zeros(1, seq_len + 1, d_model))
            layer = nn.TransformerEncoderLayer(
                d_model=d_model,
                nhead=5,
                dim_feedforward=160,
                dropout=0.20,
                batch_first=True,
            )
            self.encoder = nn.TransformerEncoder(layer, num_layers=3)
            self.norm = nn.LayerNorm(d_model)
            self.fc = nn.Linear(d_model, num_classes)

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            b = x.size(0)
            z = self.in_proj(x)
            cls = self.cls.expand(b, -1, -1)
            z = torch.cat([cls, z], dim=1)
            z = z + self.pos[:, : z.size(1)]
            z = self.encoder(z)
            z = self.norm(z[:, 0, :])
            return self.fc(z)


    class ConvTransformerLite(nn.Module):
        def __init__(self, in_features: int, seq_len: int, num_classes: int, d_model: int = 64) -> None:
            super().__init__()
            self.conv = nn.Sequential(
                nn.Conv1d(in_features, d_model, kernel_size=5, padding=2),
                nn.BatchNorm1d(d_model),
                nn.GELU(),
                nn.Conv1d(d_model, d_model, kernel_size=3, padding=1),
                nn.BatchNorm1d(d_model),
                nn.GELU(),
            )
            self.pos = nn.Parameter(torch.zeros(1, seq_len, d_model))
            layer = nn.TransformerEncoderLayer(
                d_model=d_model,
                nhead=4,
                dim_feedforward=128,
                dropout=0.20,
                batch_first=True,
            )
            self.encoder = nn.TransformerEncoder(layer, num_layers=2)
            self.norm = nn.LayerNorm(d_model)
            self.fc = nn.Linear(d_model, num_classes)

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            z = x.transpose(1, 2)
            z = self.conv(z).transpose(1, 2)
            z = z + self.pos[:, : z.size(1)]
            z = self.encoder(z)
            z = self.norm(z.mean(dim=1))
            return self.fc(z)


def _evaluate_torch_arch_input_search(
    model_name: str,
    candidates: list[dict[str, Any]],
    seq_inputs: dict[str, np.ndarray],
    labels: np.ndarray,
    splitter: StratifiedKFold,
    max_epochs: int,
    seed: int,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    if not HAS_TORCH:
        raise RuntimeError("Torch input search requested but torch is unavailable.")

    search_rows: list[dict[str, Any]] = []
    best_result: dict[str, Any] | None = None
    best_score = -1.0

    for cand in candidates:
        input_name = str(cand["input_name"])
        architecture = str(cand["architecture"])
        builder: Callable[[int, int, int], nn.Module] = cand["builder"]
        x_seq = seq_inputs[input_name]

        result = evaluate_torch_model(
            model_name=model_name,
            model_builder=builder,
            x_seq=x_seq,
            y=labels,
            splitter=splitter,
            max_epochs=max_epochs,
            seed=seed,
        )
        score = float(result["overall"]["balanced_accuracy"])
        search_rows.append(
            {
                "model": model_name,
                "architecture": architecture,
                "input_name": input_name,
                "accuracy": float(result["overall"]["accuracy"]),
                "balanced_accuracy": score,
                "f1_macro": float(result["overall"]["f1_macro"]),
            }
        )
        if score > best_score:
            best_score = score
            best_result = result
            best_result["input_name"] = input_name
            best_result["architecture"] = architecture

    if best_result is None:
        raise RuntimeError(f"No candidate evaluated for {model_name}")
    return best_result, search_rows


def run_model_training(
    features_npz: Path,
    epochs_npz: Path,
    out_dir: Path,
    seed: int = 42,
    max_epochs: int = 120,
    no_torch: bool = False,
) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    np.random.seed(seed)

    warnings.filterwarnings("ignore", category=ConvergenceWarning)

    fdata = np.load(features_npz, allow_pickle=True)
    feature_tensor = fdata["feature_tensor"].astype(np.float32)
    labels = fdata["labels"].astype(np.int64)

    edata = np.load(epochs_npz, allow_pickle=True)
    epochs = edata["eeg_epochs"].astype(np.float32)
    fs = float(np.asarray(edata["fs"]).reshape(-1)[0])
    channel_names = _to_str_list(edata["channel_names"])

    class_counts = np.bincount(labels, minlength=4)
    nonzero = class_counts[class_counts > 0]
    if nonzero.size == 0:
        raise RuntimeError("No labeled samples found.")
    min_class_count = int(nonzero.min())
    if min_class_count < 2:
        raise RuntimeError(f"Too few samples in at least one class: {class_counts.tolist()}")

    n_splits = min(5, min_class_count)
    splitter = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)

    tabular_inputs = _build_tabular_inputs(
        feature_tensor=feature_tensor,
        epochs=epochs,
        channel_names=channel_names,
        fs=fs,
    )
    seq_inputs = _build_sequence_inputs(feature_tensor=feature_tensor, epochs=epochs)

    logistic_candidates: list[dict[str, Any]] = []
    for input_name, use_pca, c_values in [
        ("hilbert_stats", False, [0.3, 1.0, 3.0]),
        ("hilbert_quantiles", False, [0.3, 1.0]),
        ("eeg_bandpower", False, [0.3, 1.0, 3.0]),
        ("eeg_asymmetry", False, [0.3, 1.0, 3.0]),
        ("combo_all_dense", False, [0.3, 1.0, 3.0]),
        ("hilbert_flat", True, [0.3, 1.0]),
        ("eeg_raw_ds4", True, [0.3, 1.0]),
        ("combo_all_raw", True, [0.3, 1.0]),
    ]:
        for c in c_values:
            logistic_candidates.append(
                {
                    "input_name": input_name,
                    "architecture": f"logreg_c{c}_{'pca' if use_pca else 'nopca'}",
                    "estimator": _make_logistic(seed=seed, c=float(c), use_pca=use_pca),
                }
            )

    svm_candidates: list[dict[str, Any]] = []
    for input_name, use_pca, specs in [
        ("hilbert_stats", False, [("rbf", 1.5), ("rbf", 4.0)]),
        ("eeg_bandpower", False, [("rbf", 2.0), ("linear", 1.0)]),
        ("eeg_asymmetry", False, [("rbf", 2.0), ("linear", 1.0)]),
        ("combo_all_dense", False, [("rbf", 2.0), ("linear", 1.0)]),
        ("hilbert_flat", True, [("rbf", 2.0), ("linear", 1.0)]),
        ("eeg_raw_ds4", True, [("rbf", 2.0), ("linear", 1.0)]),
    ]:
        for kernel, c in specs:
            svm_candidates.append(
                {
                    "input_name": input_name,
                    "architecture": f"svm_{kernel}_c{c}_{'pca' if use_pca else 'nopca'}",
                    "estimator": _make_svm(seed=seed, c=float(c), kernel=kernel, use_pca=use_pca),
                }
            )

    mlp_candidates: list[dict[str, Any]] = []
    for input_name, use_pca, specs in [
        ("hilbert_stats", False, [((64, 32), 1e-2), ((128, 64), 1e-2)]),
        ("eeg_bandpower", False, [((64, 32), 1e-2), ((128, 64), 5e-3)]),
        ("eeg_asymmetry", False, [((64, 32), 1e-2)]),
        ("combo_all_dense", False, [((128, 64), 1e-2), ((128, 64, 32), 1e-2)]),
        ("hilbert_flat", True, [((128, 64), 1e-2)]),
        ("eeg_raw_ds4", True, [((128, 64), 1e-2), ((256, 128), 5e-3)]),
        ("combo_all_raw", True, [((128, 64), 1e-2)]),
    ]:
        for hidden, alpha in specs:
            htxt = "x".join(str(x) for x in hidden)
            mlp_candidates.append(
                {
                    "input_name": input_name,
                    "architecture": f"mlp_{htxt}_a{alpha}_{'pca' if use_pca else 'nopca'}",
                    "estimator": _make_mlp(seed=seed, hidden=hidden, alpha=float(alpha), use_pca=use_pca),
                }
            )

    model_results: list[dict[str, Any]] = []
    input_search_rows: list[dict[str, Any]] = []

    best_logi, rows = _evaluate_sklearn_input_search(
        model_name="L1_LogisticRegression",
        candidates=logistic_candidates,
        input_map=tabular_inputs,
        labels=labels,
        splitter=splitter,
    )
    model_results.append(best_logi)
    input_search_rows.extend(rows)

    best_svm, rows = _evaluate_sklearn_input_search(
        model_name="SVM_RBF",
        candidates=svm_candidates,
        input_map=tabular_inputs,
        labels=labels,
        splitter=splitter,
    )
    model_results.append(best_svm)
    input_search_rows.extend(rows)

    best_mlp, rows = _evaluate_sklearn_input_search(
        model_name="MLP",
        candidates=mlp_candidates,
        input_map=tabular_inputs,
        labels=labels,
        splitter=splitter,
    )
    model_results.append(best_mlp)
    input_search_rows.extend(rows)

    if HAS_TORCH and not no_torch:
        cnn_arches: dict[str, Callable[[int, int, int], nn.Module]] = {
            "temporal_cnn": lambda feat_dim, _seq_len, n_cls: TemporalCNN(feat_dim, n_cls),
            "residual_tcn": lambda feat_dim, _seq_len, n_cls: ResidualTCN(feat_dim, n_cls),
            "inception_cnn": lambda feat_dim, _seq_len, n_cls: InceptionTemporalCNN(feat_dim, n_cls),
        }
        tf_arches: dict[str, Callable[[int, int, int], nn.Module]] = {
            "temporal_transformer": lambda feat_dim, seq_len, n_cls: TemporalTransformer(feat_dim, seq_len, n_cls),
            "cls_transformer": lambda feat_dim, seq_len, n_cls: CLSTransformer(feat_dim, seq_len, n_cls),
            "conv_transformer": lambda feat_dim, seq_len, n_cls: ConvTransformerLite(feat_dim, seq_len, n_cls),
        }

        cnn_inputs = [
            "eeg_seq_ds2",
            "eeg_seq_ds4",
            "fusion_hilbert_eeg4_seq36",
            "fusion_hilbert_eeg4diff_seq36",
            "hilbert_seq",
        ]
        tf_inputs = [
            "eeg_seq_ds4",
            "eeg_seq_ds8",
            "fusion_hilbert_eeg4_seq36",
            "fusion_hilbert_eeg8_seq36",
            "hilbert_seq",
        ]

        cnn_candidates = [
            {"input_name": inp, "architecture": arch, "builder": builder}
            for inp in cnn_inputs
            for arch, builder in cnn_arches.items()
        ]
        tf_candidates = [
            {"input_name": inp, "architecture": arch, "builder": builder}
            for inp in tf_inputs
            for arch, builder in tf_arches.items()
        ]

        best_cnn, rows = _evaluate_torch_arch_input_search(
            model_name="CNN",
            candidates=cnn_candidates,
            seq_inputs=seq_inputs,
            labels=labels,
            splitter=splitter,
            max_epochs=max_epochs,
            seed=seed,
        )
        model_results.append(best_cnn)
        input_search_rows.extend(rows)

        best_tf, rows = _evaluate_torch_arch_input_search(
            model_name="Transformer",
            candidates=tf_candidates,
            seq_inputs=seq_inputs,
            labels=labels,
            splitter=splitter,
            max_epochs=max_epochs,
            seed=seed,
        )
        model_results.append(best_tf)
        input_search_rows.extend(rows)

    search_df = pd.DataFrame(input_search_rows).sort_values(
        ["model", "balanced_accuracy"], ascending=[True, False]
    )
    input_search_csv = out_dir / "input_search_results.csv"
    search_df.to_csv(input_search_csv, index=False, encoding="utf-8")

    comparison_rows = [
        {
            "model": result["model"],
            "architecture": result.get("architecture", ""),
            "input_name": result.get("input_name", ""),
            "accuracy": result["overall"]["accuracy"],
            "balanced_accuracy": result["overall"]["balanced_accuracy"],
            "f1_macro": result["overall"]["f1_macro"],
        }
        for result in model_results
    ]
    comparison_df = pd.DataFrame(comparison_rows).sort_values("balanced_accuracy", ascending=False)
    model_comparison_csv = out_dir / "model_comparison.csv"
    comparison_df.to_csv(model_comparison_csv, index=False, encoding="utf-8")

    model_details_json = out_dir / "model_details.json"
    details = {
        "features_npz": str(features_npz),
        "epochs_npz": str(epochs_npz),
        "seed": int(seed),
        "max_epochs": int(max_epochs),
        "n_splits": int(n_splits),
        "class_counts": class_counts.tolist(),
        "tabular_inputs": {k: list(v.shape) for k, v in tabular_inputs.items()},
        "sequence_inputs": {k: list(v.shape) for k, v in seq_inputs.items()},
        "input_search_results": input_search_rows,
        "selected_model_results": model_results,
    }
    with model_details_json.open("w", encoding="utf-8") as f:
        json.dump(details, f, ensure_ascii=False, indent=2)

    print("model_comparison (best architecture/input per model):")
    print(comparison_df.to_string(index=False))
    print(f"saved={input_search_csv}")
    print(f"saved={model_comparison_csv}")
    print(f"saved={model_details_json}")

    return {
        "input_search_csv": input_search_csv,
        "model_comparison_csv": model_comparison_csv,
        "model_details_json": model_details_json,
        "model_results": model_results,
    }


def main() -> None:
    args = parse_args()
    run_model_training(
        features_npz=args.features_npz,
        epochs_npz=args.epochs_npz,
        out_dir=args.out_dir,
        seed=args.seed,
        max_epochs=args.max_epochs,
        no_torch=args.no_torch,
    )


if __name__ == "__main__":
    main()
