from __future__ import annotations

import argparse
import copy
import json
import math
import random
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train and evaluate per-band left/right CNN models for topomap images."
    )
    parser.add_argument(
        "--tensor-npz",
        type=Path,
        default=Path("analysis_results/topomap_visuals/bandwise_topomap_tensors.npz"),
        help="Bandwise tensor NPZ generated by build_bandwise_topomap_dataset.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("analysis_results/topomap_visuals"),
        help="Output directory.",
    )
    parser.add_argument("--epochs", type=int, default=90)
    parser.add_argument("--patience", type=int, default=16)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--lr", type=float, default=8e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--n-splits", type=int, default=5)
    parser.add_argument("--val-frac", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def stratified_folds(y: np.ndarray, n_splits: int, seed: int) -> list[tuple[np.ndarray, np.ndarray]]:
    if n_splits < 2:
        raise RuntimeError("n_splits must be >=2")
    y = y.astype(np.int64)
    classes = np.unique(y)
    if classes.size != 2:
        raise RuntimeError(f"Binary labels required, got {classes.tolist()}")

    rng = np.random.default_rng(seed)
    fold_bins: list[list[int]] = [[] for _ in range(n_splits)]
    for c in classes.tolist():
        idx = np.flatnonzero(y == c)
        if idx.size < n_splits:
            raise RuntimeError(f"Class {c} has only {idx.size} samples for n_splits={n_splits}")
        idx = idx.copy()
        rng.shuffle(idx)
        for i, sample_idx in enumerate(idx.tolist()):
            fold_bins[i % n_splits].append(int(sample_idx))

    all_idx = np.arange(y.size, dtype=np.int64)
    folds: list[tuple[np.ndarray, np.ndarray]] = []
    for fi in range(n_splits):
        te = np.array(sorted(fold_bins[fi]), dtype=np.int64)
        tr = np.setdiff1d(all_idx, te, assume_unique=False)
        folds.append((tr, te))
    return folds


def stratified_train_val_split(
    y: np.ndarray,
    train_idx: np.ndarray,
    val_frac: float,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    if not (0.0 < val_frac < 0.5):
        raise RuntimeError("val_frac must be in (0, 0.5)")
    rng = np.random.default_rng(seed)
    train_idx = np.array(train_idx, dtype=np.int64)

    tr_parts: list[np.ndarray] = []
    va_parts: list[np.ndarray] = []
    for c in (0, 1):
        cls = train_idx[y[train_idx] == c]
        cls = cls.copy()
        rng.shuffle(cls)
        n = cls.size
        n_val = max(1, int(round(n * val_frac)))
        n_val = min(n_val, n - 1)
        va_parts.append(cls[:n_val])
        tr_parts.append(cls[n_val:])

    tr = np.concatenate(tr_parts).astype(np.int64)
    va = np.concatenate(va_parts).astype(np.int64)
    rng.shuffle(tr)
    rng.shuffle(va)
    return tr, va


def binary_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
    y_true = y_true.astype(np.int64).reshape(-1)
    y_pred = y_pred.astype(np.int64).reshape(-1)
    tp = int(np.sum((y_true == 1) & (y_pred == 1)))
    tn = int(np.sum((y_true == 0) & (y_pred == 0)))
    fp = int(np.sum((y_true == 0) & (y_pred == 1)))
    fn = int(np.sum((y_true == 1) & (y_pred == 0)))
    n = max(y_true.size, 1)
    acc = (tp + tn) / n
    tpr = tp / max(tp + fn, 1)
    tnr = tn / max(tn + fp, 1)
    bal_acc = 0.5 * (tpr + tnr)
    precision = tp / max(tp + fp, 1)
    recall = tpr
    f1 = 2.0 * precision * recall / max(precision + recall, 1e-9)
    return {
        "accuracy": float(acc),
        "balanced_accuracy": float(bal_acc),
        "f1": float(f1),
        "tp": float(tp),
        "tn": float(tn),
        "fp": float(fp),
        "fn": float(fn),
    }


class TopomapDataset(Dataset[tuple[torch.Tensor, torch.Tensor]]):
    def __init__(
        self,
        x: np.ndarray,
        y: np.ndarray,
        idx: np.ndarray,
        mean: np.ndarray,
        std: np.ndarray,
        augment: bool,
    ) -> None:
        self.x = torch.from_numpy(x[idx].astype(np.float32))
        self.y = torch.from_numpy(y[idx].astype(np.float32))
        self.mean = torch.from_numpy(mean.astype(np.float32))
        self.std = torch.from_numpy(std.astype(np.float32))
        self.augment = augment

    def __len__(self) -> int:
        return int(self.x.shape[0])

    def __getitem__(self, i: int) -> tuple[torch.Tensor, torch.Tensor]:
        xi = (self.x[i] - self.mean) / self.std
        if self.augment:
            noise = torch.randn_like(xi) * 0.015
            scale = 1.0 + 0.06 * torch.randn((xi.shape[0], 1, 1), dtype=xi.dtype)
            shift = 0.02 * torch.randn((xi.shape[0], 1, 1), dtype=xi.dtype)
            xi = xi * scale + shift + noise
        return xi, self.y[i]


class ResidualBlock(nn.Module):
    def __init__(self, in_ch: int, out_ch: int, stride: int, dropout: float) -> None:
        super().__init__()
        self.conv1 = nn.Conv2d(in_ch, out_ch, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_ch)
        self.conv2 = nn.Conv2d(out_ch, out_ch, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_ch)
        self.act = nn.GELU()
        self.drop = nn.Dropout2d(dropout) if dropout > 0 else nn.Identity()
        if stride != 1 or in_ch != out_ch:
            self.skip = nn.Sequential(
                nn.Conv2d(in_ch, out_ch, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(out_ch),
            )
        else:
            self.skip = nn.Identity()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        h = self.conv1(x)
        h = self.bn1(h)
        h = self.act(h)
        h = self.drop(h)
        h = self.conv2(h)
        h = self.bn2(h)
        return self.act(h + self.skip(x))


class LargeEEGCNN(nn.Module):
    def __init__(self, in_ch: int) -> None:
        super().__init__()
        self.stem = nn.Sequential(
            nn.Conv2d(in_ch, 64, kernel_size=7, stride=2, padding=3, bias=False),
            nn.BatchNorm2d(64),
            nn.GELU(),
            nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.GELU(),
        )
        self.stage1 = nn.Sequential(
            ResidualBlock(64, 64, stride=1, dropout=0.04),
            ResidualBlock(64, 64, stride=1, dropout=0.04),
        )
        self.stage2 = nn.Sequential(
            ResidualBlock(64, 128, stride=2, dropout=0.07),
            ResidualBlock(128, 128, stride=1, dropout=0.07),
        )
        self.stage3 = nn.Sequential(
            ResidualBlock(128, 256, stride=2, dropout=0.10),
            ResidualBlock(256, 256, stride=1, dropout=0.10),
        )
        self.stage4 = nn.Sequential(
            ResidualBlock(256, 384, stride=2, dropout=0.10),
            ResidualBlock(384, 384, stride=1, dropout=0.10),
        )
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(384, 768),
            nn.GELU(),
            nn.Dropout(0.45),
            nn.Linear(768, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.stem(x)
        x = self.stage1(x)
        x = self.stage2(x)
        x = self.stage3(x)
        x = self.stage4(x)
        return self.head(x).squeeze(1)


def parameter_count(model: nn.Module) -> int:
    return int(sum(p.numel() for p in model.parameters()))


@torch.no_grad()
def evaluate_binary(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    criterion: nn.Module,
) -> tuple[float, np.ndarray, np.ndarray]:
    model.eval()
    probs: list[np.ndarray] = []
    labels: list[np.ndarray] = []
    total_loss = 0.0
    total_n = 0
    for xb, yb in loader:
        xb = xb.to(device, non_blocking=True)
        yb = yb.to(device, non_blocking=True)
        logits = model(xb)
        loss = criterion(logits, yb)
        bs = int(yb.shape[0])
        total_loss += float(loss.item()) * bs
        total_n += bs
        probs.append(torch.sigmoid(logits).cpu().numpy().astype(np.float64))
        labels.append(yb.cpu().numpy().astype(np.int64))
    all_prob = np.concatenate(probs, axis=0)
    all_label = np.concatenate(labels, axis=0)
    return total_loss / max(total_n, 1), all_prob, all_label


@dataclass
class FoldResult:
    fold: int
    best_epoch: int
    val_balanced_accuracy: float
    test_accuracy: float
    test_balanced_accuracy: float
    test_f1: float
    tp: int
    tn: int
    fp: int
    fn: int


def run_one_model(
    x: np.ndarray,
    y: np.ndarray,
    n_splits: int,
    val_frac: float,
    seed: int,
    epochs: int,
    patience: int,
    batch_size: int,
    lr: float,
    weight_decay: float,
    device: torch.device,
) -> dict[str, Any]:
    folds = stratified_folds(y=y, n_splits=n_splits, seed=seed)
    fold_rows: list[FoldResult] = []
    all_true: list[int] = []
    all_pred: list[int] = []
    params = 0

    for fold_id, (tr_all, te_idx) in enumerate(folds, start=1):
        tr_idx, va_idx = stratified_train_val_split(
            y=y,
            train_idx=tr_all,
            val_frac=val_frac,
            seed=seed + fold_id,
        )

        mean = np.mean(x[tr_idx], axis=(0, 2, 3)).astype(np.float32).reshape(-1, 1, 1)
        std = np.std(x[tr_idx], axis=(0, 2, 3)).astype(np.float32).reshape(-1, 1, 1)
        std = np.maximum(std, 1e-6)

        tr_ds = TopomapDataset(x=x, y=y, idx=tr_idx, mean=mean, std=std, augment=True)
        va_ds = TopomapDataset(x=x, y=y, idx=va_idx, mean=mean, std=std, augment=False)
        te_ds = TopomapDataset(x=x, y=y, idx=te_idx, mean=mean, std=std, augment=False)

        tr_loader = DataLoader(tr_ds, batch_size=batch_size, shuffle=True, drop_last=False)
        va_loader = DataLoader(va_ds, batch_size=batch_size, shuffle=False, drop_last=False)
        te_loader = DataLoader(te_ds, batch_size=batch_size, shuffle=False, drop_last=False)

        model = LargeEEGCNN(in_ch=int(x.shape[1])).to(device)
        params = parameter_count(model)

        pos_count = max(float(np.sum(y[tr_idx] == 1)), 1.0)
        neg_count = max(float(np.sum(y[tr_idx] == 0)), 1.0)
        pos_weight = torch.tensor([neg_count / pos_count], dtype=torch.float32, device=device)
        criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

        best_state: dict[str, torch.Tensor] | None = None
        best_epoch = 0
        best_val_loss = float("inf")
        best_val_bal = -1.0
        wait = 0

        for epoch in range(1, epochs + 1):
            model.train()
            for xb, yb in tr_loader:
                xb = xb.to(device, non_blocking=True)
                yb = yb.to(device, non_blocking=True)
                optimizer.zero_grad(set_to_none=True)
                logits = model(xb)
                loss = criterion(logits, yb)
                loss.backward()
                optimizer.step()

            va_loss, va_prob, va_true = evaluate_binary(model, va_loader, device=device, criterion=criterion)
            va_pred = (va_prob >= 0.5).astype(np.int64)
            va_metric = binary_metrics(va_true, va_pred)
            va_bal = float(va_metric["balanced_accuracy"])

            improved = va_loss < best_val_loss - 1e-5
            if improved:
                best_val_loss = va_loss
                best_val_bal = va_bal
                best_epoch = epoch
                best_state = copy.deepcopy(model.state_dict())
                wait = 0
            else:
                wait += 1
                if wait >= patience:
                    break

        if best_state is None:
            best_state = copy.deepcopy(model.state_dict())
            best_epoch = epochs

        model.load_state_dict(best_state)
        _te_loss, te_prob, te_true = evaluate_binary(model, te_loader, device=device, criterion=criterion)
        te_pred = (te_prob >= 0.5).astype(np.int64)
        te_metric = binary_metrics(te_true, te_pred)

        all_true.extend(te_true.tolist())
        all_pred.extend(te_pred.tolist())
        fold_rows.append(
            FoldResult(
                fold=fold_id,
                best_epoch=int(best_epoch),
                val_balanced_accuracy=float(best_val_bal),
                test_accuracy=float(te_metric["accuracy"]),
                test_balanced_accuracy=float(te_metric["balanced_accuracy"]),
                test_f1=float(te_metric["f1"]),
                tp=int(te_metric["tp"]),
                tn=int(te_metric["tn"]),
                fp=int(te_metric["fp"]),
                fn=int(te_metric["fn"]),
            )
        )

    y_true_all = np.array(all_true, dtype=np.int64)
    y_pred_all = np.array(all_pred, dtype=np.int64)
    overall = binary_metrics(y_true_all, y_pred_all)
    return {
        "params": int(params),
        "folds": [asdict(r) for r in fold_rows],
        "overall": overall,
    }


def run_training(
    tensor_npz: Path,
    out_dir: Path,
    epochs: int,
    patience: int,
    batch_size: int,
    lr: float,
    weight_decay: float,
    n_splits: int,
    val_frac: float,
    seed: int,
) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    set_seed(seed)

    data = np.load(tensor_npz, allow_pickle=True)
    power = data["power_images"].astype(np.float32)  # [N, B, W, H, W]
    phase = data["phase_images"].astype(np.float32)  # [N, B, W, H, W]
    y = data["labels_bin"].astype(np.int64)
    bands = data["bands_hz"].astype(np.float32)

    if power.shape != phase.shape:
        raise RuntimeError("power_images and phase_images shape mismatch")
    if power.shape[0] != y.shape[0]:
        raise RuntimeError("Sample size mismatch between tensors and labels")

    n_samples, n_bands, n_windows, h, w = power.shape
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    all_results: list[dict[str, Any]] = []
    for mode, arr in (("power_only", power), ("phase_only", phase)):
        for bi in range(n_bands):
            band_lo = float(bands[bi, 0])
            band_hi = float(bands[bi, 1])
            band_name = f"{int(band_lo)}-{int(band_hi)}Hz"
            x = arr[:, bi, :, :, :]  # [N, W, H, W]
            set_seed(seed + bi + (1000 if mode == "phase_only" else 0))
            model_result = run_one_model(
                x=x,
                y=y,
                n_splits=n_splits,
                val_frac=val_frac,
                seed=seed + bi,
                epochs=epochs,
                patience=patience,
                batch_size=batch_size,
                lr=lr,
                weight_decay=weight_decay,
                device=device,
            )
            all_results.append(
                {
                    "mode": mode,
                    "band_hz": band_name,
                    "band_index": int(bi),
                    "params": model_result["params"],
                    "overall": model_result["overall"],
                    "folds": model_result["folds"],
                }
            )

    rows: list[dict[str, Any]] = []
    fold_rows: list[dict[str, Any]] = []
    for r in all_results:
        ov = r["overall"]
        rows.append(
            {
                "mode": r["mode"],
                "band_hz": r["band_hz"],
                "band_index": r["band_index"],
                "params": r["params"],
                "samples": int(n_samples),
                "windows_per_sample": int(n_windows),
                "accuracy": ov["accuracy"],
                "balanced_accuracy": ov["balanced_accuracy"],
                "f1": ov["f1"],
                "tp": ov["tp"],
                "tn": ov["tn"],
                "fp": ov["fp"],
                "fn": ov["fn"],
            }
        )
        for fold in r["folds"]:
            fold_rows.append(
                {
                    "mode": r["mode"],
                    "band_hz": r["band_hz"],
                    "band_index": r["band_index"],
                    "params": r["params"],
                    **fold,
                }
            )

    comparison_df = pd.DataFrame(rows).sort_values(
        ["balanced_accuracy", "accuracy", "f1"],
        ascending=[False, False, False],
    )
    folds_df = pd.DataFrame(fold_rows).sort_values(["mode", "band_index", "fold"])

    comparison_csv = out_dir / "bandwise_lr_model_comparison.csv"
    folds_csv = out_dir / "bandwise_lr_model_folds.csv"
    details_json = out_dir / "bandwise_lr_model_details.json"
    comparison_df.to_csv(comparison_csv, index=False, encoding="utf-8")
    folds_df.to_csv(folds_csv, index=False, encoding="utf-8")

    details = {
        "tensor_npz": str(tensor_npz),
        "device": str(device),
        "shape": {
            "samples": int(n_samples),
            "bands": int(n_bands),
            "windows": int(n_windows),
            "height": int(h),
            "width": int(w),
        },
        "settings": {
            "epochs": int(epochs),
            "patience": int(patience),
            "batch_size": int(batch_size),
            "lr": float(lr),
            "weight_decay": float(weight_decay),
            "n_splits": int(n_splits),
            "val_frac": float(val_frac),
            "seed": int(seed),
        },
        "class_counts": {
            "left(0)": int(np.sum(y == 0)),
            "right(1)": int(np.sum(y == 1)),
        },
        "results": all_results,
    }
    with details_json.open("w", encoding="utf-8") as f:
        json.dump(details, f, ensure_ascii=False, indent=2)

    best = comparison_df.iloc[0].to_dict() if not comparison_df.empty else {}
    return {
        "comparison_csv": comparison_csv,
        "folds_csv": folds_csv,
        "details_json": details_json,
        "best_mode": str(best.get("mode", "")),
        "best_band_hz": str(best.get("band_hz", "")),
        "best_balanced_accuracy": float(best.get("balanced_accuracy", math.nan)),
    }


def main() -> None:
    args = parse_args()
    result = run_training(
        tensor_npz=args.tensor_npz,
        out_dir=args.out_dir,
        epochs=args.epochs,
        patience=args.patience,
        batch_size=args.batch_size,
        lr=args.lr,
        weight_decay=args.weight_decay,
        n_splits=args.n_splits,
        val_frac=args.val_frac,
        seed=args.seed,
    )
    print(f"saved={result['comparison_csv']}")
    print(f"saved={result['folds_csv']}")
    print(f"saved={result['details_json']}")
    print(f"best_mode={result['best_mode']}")
    print(f"best_band_hz={result['best_band_hz']}")
    print(f"best_balanced_accuracy={result['best_balanced_accuracy']:.4f}")


if __name__ == "__main__":
    main()
