from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import mne
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from scipy.signal import butter, hilbert, sosfiltfilt

BANDS_HZ: list[tuple[float, float]] = [
    (4.0, 8.0),
    (8.0, 12.0),
    (12.0, 16.0),
    (16.0, 20.0),
    (20.0, 24.0),
    (24.0, 28.0),
    (28.0, 32.0),
    (32.0, 40.0),
]

EEG_COORDS: dict[str, tuple[float, float]] = {
    "AF7": (-0.60, 0.90),
    "Fp1": (-0.35, 1.00),
    "Fp2": (0.35, 1.00),
    "AF8": (0.60, 0.90),
    "F3": (-0.50, 0.45),
    "F4": (0.50, 0.45),
    "P3": (-0.50, -0.35),
    "P4": (0.50, -0.35),
    "P7": (-0.90, -0.25),
    "O1": (-0.35, -0.90),
    "O2": (0.35, -0.90),
    "P8": (0.90, -0.25),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create per-trial MNE topomap images for left/right imagery epochs "
            "(band power + phase-gradient flow)."
        )
    )
    parser.add_argument(
        "--epochs-npz",
        type=Path,
        default=Path("analysis_results/imagine_epochs_4class.npz"),
        help="Epoch NPZ generated by extract_imagine_epochs.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("analysis_results/topomap_visuals"),
        help="Directory to save output images.",
    )
    parser.add_argument(
        "--directions",
        nargs="+",
        default=["left", "right"],
        help="Directions to visualize (default: left right).",
    )
    parser.add_argument(
        "--trials-per-direction",
        type=int,
        default=3,
        help="Number of trials to visualize for each direction.",
    )
    parser.add_argument(
        "--window-sec",
        type=float,
        default=0.5,
        help="Window size in seconds for within-epoch change plots.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=160,
        help="DPI for saved images.",
    )
    parser.add_argument(
        "--grid-size",
        type=int,
        default=96,
        help="Grid size for exported topomap image tensors.",
    )
    return parser.parse_args()


def _to_str_list(values: np.ndarray) -> list[str]:
    out: list[str] = []
    for value in values.tolist():
        if isinstance(value, bytes):
            out.append(value.decode("utf-8"))
        else:
            out.append(str(value))
    return out


def _safe_direction_array(data: np.lib.npyio.NpzFile, labels: np.ndarray) -> np.ndarray:
    if "direction" in data.files:
        raw = data["direction"]
        if raw.dtype.kind in {"S", "U", "O"}:
            return np.array(_to_str_list(raw), dtype=object)

    id_to_direction = {0: "front", 1: "back", 2: "left", 3: "right"}
    return np.array([id_to_direction.get(int(v), "") for v in labels.tolist()], dtype=object)


def _window_starts(n_samples: int, fs: float, window_sec: float) -> tuple[np.ndarray, int]:
    win = int(round(window_sec * fs))
    if win < 2:
        raise RuntimeError(f"window_sec is too short for fs={fs}: {window_sec}")
    starts = np.arange(0, n_samples - win + 1, win, dtype=np.int64)
    if starts.size == 0:
        starts = np.array([0], dtype=np.int64)
        win = n_samples
    return starts, win


def _phase_mean(diff: np.ndarray) -> float:
    return float(np.angle(np.mean(np.exp(1j * diff))))


def _node_phase_gradients(phase_window: np.ndarray, positions: np.ndarray) -> np.ndarray:
    n_ch = phase_window.shape[0]
    grads = np.zeros((n_ch, 2), dtype=np.float64)
    for i in range(n_ch):
        w = 0.0
        for j in range(n_ch):
            if i == j:
                continue
            dx = float(positions[j, 0] - positions[i, 0])
            dy = float(positions[j, 1] - positions[i, 1])
            dist2 = dx * dx + dy * dy
            if dist2 <= 1e-12:
                continue
            phase_diff = phase_window[j] - phase_window[i]
            mean_diff = _phase_mean(phase_diff)
            inv = 1.0 / dist2
            grads[i, 0] += mean_diff * dx * inv
            grads[i, 1] += mean_diff * dy * inv
            w += inv
        if w > 0.0:
            grads[i] /= w
    return grads


def _compute_epoch_maps(
    epoch: np.ndarray,
    fs: float,
    positions: np.ndarray,
    bands_hz: list[tuple[float, float]],
    starts: np.ndarray,
    win_len: int,
) -> tuple[np.ndarray, np.ndarray]:
    n_ch = epoch.shape[0]
    n_bands = len(bands_hz)
    n_windows = starts.size
    power_maps = np.zeros((n_bands, n_windows, n_ch), dtype=np.float64)
    phase_grads = np.zeros((n_bands, n_windows, n_ch, 2), dtype=np.float64)

    nyq = fs * 0.5
    for bi, (lo, hi) in enumerate(bands_hz):
        if lo <= 0 or hi >= nyq:
            raise RuntimeError(f"Band out of range: ({lo}, {hi}) with Nyquist={nyq}")
        sos = butter(4, [lo / nyq, hi / nyq], btype="bandpass", output="sos")
        filtered = sosfiltfilt(sos, epoch, axis=1)
        analytic = hilbert(filtered, axis=1)
        band_power = np.abs(analytic) ** 2
        band_phase = np.angle(analytic)

        for wi, st in enumerate(starts):
            ed = int(st + win_len)
            p = np.mean(band_power[:, st:ed], axis=1)
            power_maps[bi, wi, :] = np.log10(np.maximum(p, 1e-12))
            phase_grads[bi, wi, :, :] = _node_phase_gradients(band_phase[:, st:ed], positions)

    return power_maps, phase_grads


def _plot_grid(
    values: np.ndarray,
    positions: np.ndarray,
    starts: np.ndarray,
    win_len: int,
    fs: float,
    band_names: list[str],
    title: str,
    cbar_label: str,
    out_path: Path,
    dpi: int,
    vectors: np.ndarray | None = None,
) -> None:
    n_bands, n_windows, _n_ch = values.shape
    fig, axes = plt.subplots(
        nrows=n_bands,
        ncols=n_windows,
        figsize=(3.0 * n_windows, 2.0 * n_bands),
        constrained_layout=True,
    )
    axes_2d = np.atleast_2d(axes)
    vmax = float(np.quantile(np.abs(values), 0.98))
    vmax = max(vmax, 1e-6)
    image = None

    for bi in range(n_bands):
        for wi in range(n_windows):
            ax = axes_2d[bi, wi]
            image, _ = mne.viz.plot_topomap(
                values[bi, wi, :],
                positions,
                axes=ax,
                show=False,
                cmap="RdBu_r",
                contours=5,
                vlim=(-vmax, vmax),
                sensors=True,
                names=None,
            )
            if vectors is not None:
                quiver_scale = max(float(np.quantile(np.linalg.norm(vectors, axis=-1), 0.95)), 1e-9)
                u = vectors[bi, wi, :, 0] / quiver_scale * 0.25
                v = vectors[bi, wi, :, 1] / quiver_scale * 0.25
                ax.quiver(
                    positions[:, 0],
                    positions[:, 1],
                    u,
                    v,
                    angles="xy",
                    scale_units="xy",
                    scale=1.0,
                    width=0.008,
                    color="black",
                    alpha=0.85,
                )
            if bi == 0:
                t0 = float(starts[wi] / fs)
                t1 = float((starts[wi] + win_len) / fs)
                ax.set_title(f"{t0:.1f}-{t1:.1f}s", fontsize=9)
            if wi == 0:
                ax.set_ylabel(band_names[bi], fontsize=9)

    fig.suptitle(title, fontsize=12)
    assert image is not None
    cbar = fig.colorbar(image, ax=axes_2d.ravel().tolist(), shrink=0.6, pad=0.02)
    cbar.set_label(cbar_label)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=dpi)
    plt.close(fig)


def _prepare_grid(grid_size: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if grid_size < 16:
        raise RuntimeError("grid_size must be at least 16")
    axis = np.linspace(-1.0, 1.0, grid_size, dtype=np.float64)
    xx, yy = np.meshgrid(axis, axis)
    mask = (xx * xx + yy * yy) <= 1.0
    return xx, yy, mask


def _idw_topomap(
    channel_values: np.ndarray,
    positions: np.ndarray,
    xx: np.ndarray,
    yy: np.ndarray,
    mask: np.ndarray,
) -> np.ndarray:
    vals = channel_values.reshape(-1, 1, 1)
    px = positions[:, 0].reshape(-1, 1, 1)
    py = positions[:, 1].reshape(-1, 1, 1)
    dist2 = (xx.reshape(1, *xx.shape) - px) ** 2 + (yy.reshape(1, *yy.shape) - py) ** 2
    w = 1.0 / np.maximum(dist2, 1e-6)
    topomap = np.sum(w * vals, axis=0) / np.maximum(np.sum(w, axis=0), 1e-9)
    topomap = topomap.astype(np.float32)
    topomap[~mask] = 0.0
    return topomap


def _maps_to_image_stack(
    values: np.ndarray,
    positions: np.ndarray,
    xx: np.ndarray,
    yy: np.ndarray,
    mask: np.ndarray,
) -> np.ndarray:
    n_bands, n_windows, _n_ch = values.shape
    channels: list[np.ndarray] = []
    for bi in range(n_bands):
        for wi in range(n_windows):
            channels.append(_idw_topomap(values[bi, wi], positions, xx=xx, yy=yy, mask=mask))
    return np.stack(channels, axis=0).astype(np.float32)


def run_visualization(
    epochs_npz: Path,
    out_dir: Path,
    directions: list[str],
    trials_per_direction: int,
    window_sec: float,
    dpi: int,
    grid_size: int,
) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)

    data = np.load(epochs_npz, allow_pickle=True)
    epochs = data["eeg_epochs"].astype(np.float64)
    labels = data["labels"].astype(np.int64)
    trials = data["trial_idx"].astype(np.int64)
    fs = float(np.asarray(data["fs"]).reshape(-1)[0])
    channel_names = _to_str_list(data["channel_names"])
    direction = _safe_direction_array(data, labels)

    missing = [ch for ch in channel_names if ch not in EEG_COORDS]
    if missing:
        raise RuntimeError(f"Missing EEG coordinates for channels: {missing}")
    positions = np.array([EEG_COORDS[ch] for ch in channel_names], dtype=np.float64)

    starts, win_len = _window_starts(n_samples=int(epochs.shape[2]), fs=fs, window_sec=window_sec)
    band_names = [f"{lo:g}-{hi:g}Hz" for lo, hi in BANDS_HZ]
    xx, yy, head_mask = _prepare_grid(grid_size)

    selected_rows: list[dict[str, Any]] = []
    avg_cache: dict[str, dict[str, list[np.ndarray]]] = {}
    tensor_power: list[np.ndarray] = []
    tensor_phase: list[np.ndarray] = []
    tensor_label_bin: list[int] = []
    tensor_trial: list[int] = []
    tensor_direction: list[str] = []
    lr_map = {"left": 0, "right": 1}

    for direction_name in directions:
        dir_mask = np.array([str(v).lower() == direction_name.lower() for v in direction], dtype=bool)
        dir_indices = np.flatnonzero(dir_mask)
        if dir_indices.size == 0:
            continue
        picked = dir_indices[: max(0, trials_per_direction)]
        avg_cache[direction_name] = {"power": [], "grad": []}

        for idx in picked.tolist():
            power_maps, phase_grads = _compute_epoch_maps(
                epoch=epochs[idx],
                fs=fs,
                positions=positions,
                bands_hz=BANDS_HZ,
                starts=starts,
                win_len=win_len,
            )

            power_maps_raw = power_maps.copy()
            phase_x_raw = phase_grads[:, :, :, 0].copy()

            power_maps_vis = power_maps_raw.copy()
            for bi in range(power_maps_vis.shape[0]):
                mean_v = float(np.mean(power_maps_vis[bi]))
                std_v = float(np.std(power_maps_vis[bi]))
                power_maps_vis[bi] = (power_maps_vis[bi] - mean_v) / max(std_v, 1e-9)

            phase_x_vis = phase_x_raw.copy()
            for bi in range(phase_x_vis.shape[0]):
                mean_v = float(np.mean(phase_x_vis[bi]))
                std_v = float(np.std(phase_x_vis[bi]))
                phase_x_vis[bi] = (phase_x_vis[bi] - mean_v) / max(std_v, 1e-9)

            power_name = f"topomap_power_{direction_name}_trial{int(trials[idx]):03d}.png"
            flow_name = f"topomap_phasegradx_{direction_name}_trial{int(trials[idx]):03d}.png"
            power_path = out_dir / power_name
            flow_path = out_dir / flow_name

            _plot_grid(
                values=power_maps_vis,
                positions=positions,
                starts=starts,
                win_len=win_len,
                fs=fs,
                band_names=band_names,
                title=f"Band Power (z-score) | direction={direction_name} trial={int(trials[idx])}",
                cbar_label="Power z-score",
                out_path=power_path,
                dpi=dpi,
                vectors=None,
            )

            _plot_grid(
                values=phase_x_vis,
                positions=positions,
                starts=starts,
                win_len=win_len,
                fs=fs,
                band_names=band_names,
                title=f"Phase Gradient X + Flow Vectors | direction={direction_name} trial={int(trials[idx])}",
                cbar_label="Phase gradient X (a.u.)",
                out_path=flow_path,
                dpi=dpi,
                vectors=phase_grads,
            )

            power_stack = _maps_to_image_stack(
                values=power_maps_raw,
                positions=positions,
                xx=xx,
                yy=yy,
                mask=head_mask,
            )
            phase_stack = _maps_to_image_stack(
                values=phase_x_raw,
                positions=positions,
                xx=xx,
                yy=yy,
                mask=head_mask,
            )

            selected_rows.append(
                {
                    "direction": direction_name,
                    "sample_index": int(idx),
                    "trial_idx": int(trials[idx]),
                    "power_png": str(power_path),
                    "phase_grad_png": str(flow_path),
                }
            )
            avg_cache[direction_name]["power"].append(power_maps_vis)
            avg_cache[direction_name]["grad"].append(phase_grads)
            if direction_name in lr_map:
                tensor_power.append(power_stack)
                tensor_phase.append(phase_stack)
                tensor_label_bin.append(lr_map[direction_name])
                tensor_trial.append(int(trials[idx]))
                tensor_direction.append(direction_name)

    for direction_name, cache in avg_cache.items():
        if not cache["power"]:
            continue
        power_avg = np.mean(np.stack(cache["power"], axis=0), axis=0)
        grad_avg = np.mean(np.stack(cache["grad"], axis=0), axis=0)

        _plot_grid(
            values=power_avg,
            positions=positions,
            starts=starts,
            win_len=win_len,
            fs=fs,
            band_names=band_names,
            title=f"Band Power Average (z-score) | direction={direction_name}",
            cbar_label="Power z-score",
            out_path=out_dir / f"topomap_power_{direction_name}_average.png",
            dpi=dpi,
            vectors=None,
        )
        _plot_grid(
            values=grad_avg[:, :, :, 0],
            positions=positions,
            starts=starts,
            win_len=win_len,
            fs=fs,
            band_names=band_names,
            title=f"Phase Gradient X Average + Flow Vectors | direction={direction_name}",
            cbar_label="Phase gradient X (a.u.)",
            out_path=out_dir / f"topomap_phasegradx_{direction_name}_average.png",
            dpi=dpi,
            vectors=grad_avg,
        )

    manifest_csv = out_dir / "topomap_manifest.csv"
    pd.DataFrame(selected_rows).to_csv(manifest_csv, index=False, encoding="utf-8")

    tensor_npz = out_dir / "topomap_image_tensors.npz"
    if tensor_power:
        np.savez_compressed(
            tensor_npz,
            power_images=np.stack(tensor_power, axis=0).astype(np.float32),
            phase_images=np.stack(tensor_phase, axis=0).astype(np.float32),
            labels_bin=np.array(tensor_label_bin, dtype=np.int64),
            trial_idx=np.array(tensor_trial, dtype=np.int64),
            direction=np.array(tensor_direction, dtype=object),
            grid_size=np.array([grid_size], dtype=np.int64),
            bands_hz=np.array(BANDS_HZ, dtype=np.float32),
            window_start_samples=starts.astype(np.int64),
            window_len_samples=np.array([win_len], dtype=np.int64),
            fs=np.array([fs], dtype=np.float64),
        )

    summary = {
        "epochs_npz": str(epochs_npz),
        "out_dir": str(out_dir),
        "sampling_rate_hz": fs,
        "bands_hz": BANDS_HZ,
        "window_sec": float(window_sec),
        "window_count": int(starts.size),
        "trials_per_direction": int(trials_per_direction),
        "selected_count": len(selected_rows),
        "manifest_csv": str(manifest_csv),
        "tensor_npz": str(tensor_npz if tensor_power else ""),
        "lr_tensor_count": int(len(tensor_power)),
        "grid_size": int(grid_size),
    }
    summary_json = out_dir / "topomap_summary.json"
    with summary_json.open("w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    return {"manifest_csv": manifest_csv, "summary_json": summary_json, "summary": summary}


def main() -> None:
    args = parse_args()
    result = run_visualization(
        epochs_npz=args.epochs_npz,
        out_dir=args.out_dir,
        directions=[str(d).strip().lower() for d in args.directions if str(d).strip()],
        trials_per_direction=args.trials_per_direction,
        window_sec=args.window_sec,
        dpi=args.dpi,
        grid_size=args.grid_size,
    )
    print(f"saved={result['manifest_csv']}")
    print(f"saved={result['summary_json']}")
    print(f"selected_count={result['summary']['selected_count']}")


if __name__ == "__main__":
    main()
